# Generated by Django 5.1.1 on 2024-09-20 19:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchedulingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_satisfaction", models.FloatField()),
                ("unassigned_shifts", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("COOK", "Cook"),
                            ("CASHIER", "Cashier"),
                            ("DISPATCH", "Dispatch"),
                            ("SANDWICH", "Sandwich"),
                            ("DRIVER", "Driver"),
                            ("RESTAURANT_MANAGER", "Restaurant Manager"),
                            ("SHIFT_SUPERVISOR", "Shift Supervisor"),
                            ("ASSISTANT_MANAGER", "Assistant Manager"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ShiftBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("MORNING", "9AM to 6PM"),
                            ("AFTERNOON", "12PM to 9PM"),
                            ("EVENING", "3PM to 12AM"),
                            ("NIGHT", "6PM to 3AM"),
                            ("LATE_NIGHT", "9PM to 6AM"),
                            ("EARLY_MORNING", "12AM to 9AM"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "max_hours_per_week",
                    models.IntegerField(
                        default=48,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "satisfaction_score",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "availability",
                    models.ManyToManyField(
                        related_name="available_employees", to="scheduler.shiftblock"
                    ),
                ),
                (
                    "preferred_shifts",
                    models.ManyToManyField(
                        related_name="preferring_employees", to="scheduler.shiftblock"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduler.shift",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shift",
            name="shift_block",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="scheduler.shiftblock"
            ),
        ),
        migrations.CreateModel(
            name="EmployeeRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("COOK", "Cook"),
                            ("CASHIER", "Cashier"),
                            ("DISPATCH", "Dispatch"),
                            ("SANDWICH", "Sandwich"),
                            ("DRIVER", "Driver"),
                            ("RESTAURANT_MANAGER", "Restaurant Manager"),
                            ("SHIFT_SUPERVISOR", "Shift Supervisor"),
                            ("ASSISTANT_MANAGER", "Assistant Manager"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="scheduler.employee",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "role")},
            },
        ),
    ]
